/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness of the API and its data
         * @description Reports whether the sky data is loaded. `starting` carries the download progress of the file currently being fetched; `degraded` means the API answers with reduced coverage. Never cached (`Cache-Control: no-store`).
         */
        get: operations["get_health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * DownloadProgress
         * @description Progress of the data file currently being downloaded at startup.
         */
        DownloadProgress: {
            /**
             * Downloaded Bytes
             * @description Bytes received so far.
             * @example 16777216
             */
            downloaded_bytes: number;
            /**
             * File
             * @description File name being downloaded into DATA_DIR.
             * @example de440s.bsp
             */
            file: string;
            /**
             * Total Bytes
             * @description Expected size of the file in bytes (0 when the server did not say).
             * @example 32726016
             */
            total_bytes: number;
        };
        /**
         * HealthResponse
         * @description Readiness report used by the Docker healthcheck and the frontend splash screen.
         */
        HealthResponse: {
            /**
             * @description Download progress; present only while `status` is `starting`.
             * @example {
             *       "downloaded_bytes": 16777216,
             *       "file": "de440s.bsp",
             *       "total_bytes": 32726016
             *     }
             */
            progress?: components["schemas"]["DownloadProgress"] | null;
            /**
             * Status
             * @description `starting` while data is being fetched or loaded, `ready` when every endpoint answers, `degraded` when the API runs with reduced coverage.
             * @example ready
             * @enum {string}
             */
            status: "starting" | "ready" | "degraded";
            /**
             * Version
             * @description Version of the `skyapi` package serving the request.
             * @example 0.1.0
             */
            version: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
