// The data credits of the About screen (INFO-4, brief l.326, plan D110): `credits.json` is
// generated by `python -m skyapi.tools.render_notices --json` from the same registry as
// `THIRD_PARTY_NOTICES.md` (never hand-edited, gated like the contract files). Every key is
// present in every entry (`null` when the registry has no value), which this wrapper checks once
// so the components read a typed, validated list.

import creditsJson from './credits.json';

export interface CreditEntry {
  /** Registry key (`de440s`, `hyg`, `nominatim`, ...). */
  key: string;
  filename: string | null;
  /** `download`, `committed`, `ui_asset`, `service`, ... as the registry classifies it. */
  kind: string;
  url: string | null;
  fallback_urls: readonly string[];
  version_or_date: string | null;
  license: string | null;
  copyright: string | null;
  attribution: string | null;
  license_text: string | null;
  notes: string | null;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function isNullableString(value: unknown): value is string | null {
  return value === null || typeof value === 'string';
}

export function isCreditEntry(value: unknown): value is CreditEntry {
  return (
    isRecord(value) &&
    typeof value.key === 'string' &&
    isNullableString(value.filename) &&
    typeof value.kind === 'string' &&
    isNullableString(value.url) &&
    Array.isArray(value.fallback_urls) &&
    value.fallback_urls.every((url: unknown) => typeof url === 'string') &&
    isNullableString(value.version_or_date) &&
    isNullableString(value.license) &&
    isNullableString(value.copyright) &&
    isNullableString(value.attribution) &&
    isNullableString(value.license_text) &&
    isNullableString(value.notes)
  );
}

/** Validate the generated document; a malformed entry fails loudly rather than rendering blanks. */
export function parseCredits(value: unknown): readonly CreditEntry[] {
  if (!Array.isArray(value)) {
    throw new Error('credits.json is not an array');
  }
  return value.map((entry: unknown, index) => {
    if (!isCreditEntry(entry)) {
      throw new Error(`credits.json entry ${String(index)} does not have the expected shape`);
    }
    return entry;
  });
}

export const CREDITS: readonly CreditEntry[] = parseCredits(creditsJson);
